# Streamlit secrets for local development
# In production, these will be set in Streamlit Cloud dashboard

OPENAI_API_KEY = "your-openai-api-key-here"
WEATHERAPI_KEY = "your-weatherapi-key-here" 
FOURSQUARE_API_KEY = "your-foursquare-api-key-here"

# Environment indicator
ENVIRONMENT = "local"